/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion_administracion;

import java.awt.BorderLayout;
import presentacion_administracion.Frm_Articulo;

import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class Frm_Things extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Things
     */
    
    Frm_Articulo frm_art = new Frm_Articulo();
    
    
    
    public Frm_Things() {
        initComponents();
        
    }
    
    public JPanel sizePanelThing(){
        return BackgroundThings;
    }
    
    private void CargarThing(JPanel jp){
        jp.setSize(1070, 740);
        jp.setLocation(0, 0);
        jPGerneral.removeAll();
        jPGerneral.add(jp, BorderLayout.CENTER);
        jPGerneral.revalidate();
        jPGerneral.repaint();
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundThings = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPSubThing = new javax.swing.JPanel();
        jbArticulo = new javax.swing.JButton();
        jbInventario = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jbTipoAticulo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jbBodega = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jPGerneral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 90));

        BackgroundThings.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundThings.setMinimumSize(new java.awt.Dimension(1070, 50));
        BackgroundThings.setPreferredSize(new java.awt.Dimension(1070, 50));
        BackgroundThings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BackgroundThings.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jPSubThing.setBackground(new java.awt.Color(50, 130, 184));
        jPSubThing.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbArticulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbArticulo.setText("Articulo");
        jbArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbArticuloActionPerformed(evt);
            }
        });
        jPSubThing.add(jbArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 240, 50));

        jbInventario.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbInventario.setText("Inventario");
        jbInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInventarioActionPerformed(evt);
            }
        });
        jPSubThing.add(jbInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 240, 50));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPSubThing.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 10, 30));

        jbTipoAticulo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbTipoAticulo.setText("Tipo Aticulo");
        jbTipoAticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTipoAticuloActionPerformed(evt);
            }
        });
        jPSubThing.add(jbTipoAticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 230, 50));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPSubThing.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 10, 30));

        jbBodega.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jbBodega.setText("Bodega");
        jbBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBodegaActionPerformed(evt);
            }
        });
        jPSubThing.add(jbBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 50));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPSubThing.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 10, 30));

        BackgroundThings.add(jPSubThing, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 80));

        jPGerneral.setBackground(new java.awt.Color(187, 225, 250));

        javax.swing.GroupLayout jPGerneralLayout = new javax.swing.GroupLayout(jPGerneral);
        jPGerneral.setLayout(jPGerneralLayout);
        jPGerneralLayout.setHorizontalGroup(
            jPGerneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        jPGerneralLayout.setVerticalGroup(
            jPGerneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        BackgroundThings.add(jPGerneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1070, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundThings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundThings, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbInventarioActionPerformed

    private void jbArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbArticuloActionPerformed
        // TODO add your handling code here:
        CargarThing(frm_art.sizePanelArticulo());
    }//GEN-LAST:event_jbArticuloActionPerformed

    private void jbBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBodegaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBodegaActionPerformed

    private void jbTipoAticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTipoAticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbTipoAticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Things.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Things.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Things.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Things.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Things().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundThings;
    private javax.swing.JPanel jPGerneral;
    private javax.swing.JPanel jPSubThing;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbArticulo;
    private javax.swing.JButton jbBodega;
    private javax.swing.JButton jbInventario;
    private javax.swing.JButton jbTipoAticulo;
    // End of variables declaration//GEN-END:variables
}
