package presentacion_administracion;

import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class Frm_Inventario extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Inventario
     */
    public Frm_Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public JPanel sizePanelInventario(){
        return jpBackground;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jBNew = new javax.swing.JButton();
        jBDelete = new javax.swing.JButton();
        jDEdit = new javax.swing.JButton();
        jBClean = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTID2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTDate = new com.toedter.calendar.JDateChooser();
        jcTipoArticulo = new javax.swing.JComboBox<>();
        jcTipoArticulo1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTID4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTID5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTID6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTID3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBackground.setBackground(new java.awt.Color(153, 204, 255));
        jpBackground.setPreferredSize(new java.awt.Dimension(1070, 650));
        jpBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 36)); // NOI18N
        jLabel5.setText("Inventario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 300, 10));

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Invetario.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 60, 60));

        jBNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/save.png"))); // NOI18N
        jBNew.setText("Nuevo");
        jBNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNewActionPerformed(evt);
            }
        });
        jPanel1.add(jBNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 140, 40));

        jBDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/basura.png"))); // NOI18N
        jBDelete.setText("Eliminar");
        jPanel1.add(jBDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 140, 40));

        jDEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/editar.png"))); // NOI18N
        jDEdit.setText("Editar");
        jPanel1.add(jDEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 140, 40));

        jBClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/limpio.png"))); // NOI18N
        jBClean.setText("Limpiar");
        jBClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCleanActionPerformed(evt);
            }
        });
        jPanel1.add(jBClean, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 250, 140, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("Saldo Final:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 30, 30));

        jTID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTID2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 200, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Bodega ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Fecha de Ingreso:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jTDate.setBackground(new java.awt.Color(255, 255, 255));
        jTDate.setForeground(new java.awt.Color(255, 255, 255));
        jTDate.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(jTDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, 30));

        jcTipoArticulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        jPanel1.add(jcTipoArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 30));

        jcTipoArticulo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar..." }));
        jPanel1.add(jcTipoArticulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setText("Articulo ID:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jTID4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTID4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setText("Cantidad Inicial:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, 30));

        jTID5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTID5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTID5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 200, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setText("Movimientos Positivos:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        jTID6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTID6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTID6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 200, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("Movimientos Negativos:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        jTID3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTID3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 200, 30));

        jpBackground.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1030, 340));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "InventarioID", "BodegaID", "ArticuloID", "Cantidad_Inicial", "Movimientos_Positivos", "Movimientos_Negativos", "Fecha", "Saldo_Final"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jpBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 1070, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNewActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBNewActionPerformed

    private void jBCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCleanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jBCleanActionPerformed

    private void jTID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTID2ActionPerformed

    private void jTID4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTID4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTID4ActionPerformed

    private void jTID5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTID5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTID5ActionPerformed

    private void jTID6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTID6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTID6ActionPerformed

    private void jTID3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTID3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTID3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with thjpBackgroundlt look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBClean;
    private javax.swing.JButton jBDelete;
    private javax.swing.JButton jBNew;
    private javax.swing.JButton jDEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser jTDate;
    private javax.swing.JTextField jTID2;
    private javax.swing.JTextField jTID3;
    private javax.swing.JTextField jTID4;
    private javax.swing.JTextField jTID5;
    private javax.swing.JTextField jTID6;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcTipoArticulo;
    private javax.swing.JComboBox<String> jcTipoArticulo1;
    private javax.swing.JPanel jpBackground;
    // End of variables declaration//GEN-END:variables
}
